language: java

install: mvn install -DskipTests=true -P full -B

notifications:
  email:
    recipients:
      - cjnolet@gmail.com
      - ceraw79@gmail.com
      - smonaghan000@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
